:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:logfile: ./log/sidekiq.log
:concurrency: 10
:queues:
  - default
  - test

:schedule:
  scraping_scheduler:
    cron: '* 1 * * * *'
    class: ScrapingScheduler
