class HallMaster < ActiveHash::Base
  self.data = [
    { id: 0, prefecture_id: 0, search_name: 'その他のホール', name: 'その他のホール' },
    { id: 1, prefecture_id: 1, search_name: '小樽市民,小樽市市民', name: '小樽市民会館' },
    { id: 2, prefecture_id: 1, search_name: '帯広市民、帯広市市民', name: '帯広市民文化ホール' },
    { id: 3, prefecture_id: 1, search_name: 'ルーテル', name: 'ザ・ルーテルホール' },
    { id: 4, prefecture_id: 1, search_name: '札幌コンサート,キタラ,北羅,Kitara,KITARA,kitara,ＫＩＴＡＲＡ', name: '札幌コンサートホールKitara' },
    { id: 5, prefecture_id: 2, search_name: '弘前市民,弘前市市民', name: '弘前市民会館' },
    { id: 6, prefecture_id: 3, search_name: '盛岡市民文化,盛岡市市民文化', name: '盛岡市民文化ホール' },
    { id: 7, prefecture_id: 4, search_name: '仙台市民会館,仙台市市民会館', name: '仙台市民会館' },
    { id: 8, prefecture_id: 4, search_name: '太白文化,太白区文化,楽楽楽', name: '太白区文化センター・楽楽楽ホール' },
    { id: 9, prefecture_id: 4, search_name: 'エレクトロン', name: '東京エレクトロンホール宮城' },
    { id: 10, prefecture_id: 4, search_name: '東北大学,川内萩', name: '東北大学百周年記念会館 川内萩ホール' },
    { id: 11, prefecture_id: 4, search_name: '日立システム,仙台市青年,仙台青年', name: '日立システムズホール仙台（仙台市青年文化センター）' },
    { id: 12, prefecture_id: 5, search_name: '横手市民,横手市市民', name: '横手市民会館' },
    { id: 13, prefecture_id: 7, search_name: '相馬市民,相馬市市民', name: '相馬市民会館' },
    { id: 14, prefecture_id: 7, search_name: '福島市音楽堂,福島市音楽堂', name: '福島市音楽堂' },
    { id: 15, prefecture_id: 8, search_name: 'アルスホール', name: 'アルスホール' },
    { id: 16, prefecture_id: 8, search_name: '茨城県民文化,茨城県立県民文化,茨城県立文化', name: '茨城県立県民文化センター' },
    { id: 17, prefecture_id: 8, search_name: '土浦市民,土浦市市民', name: '土浦市民会館' },
    { id: 18, prefecture_id: 8, search_name: '取手市立市民,取手市民,取手市市民', name: '取手市立市民会館' },
    { id: 19, prefecture_id: 8, search_name: 'ノバホール', name: 'ノバホール' },
    { id: 20, prefecture_id: 8, search_name: '坂東市市民,坂東市民,ベルフォーレ', name: '坂東市民音楽ホール・ベルフォーレ' },
    { id: 21, prefecture_id: 8, search_name: 'ひたちなか市文化,ひたちなか文化', name: 'ひたちなか市文化会館' },
    { id: 22, prefecture_id: 8, search_name: '水戸芸術館', name: '水戸芸術館' },
    { id: 23, prefecture_id: 8, search_name: '龍ヶ崎市文化,龍ヶ崎文化,龍ヶ崎市民文化', name: '龍ヶ崎市文化会館' },
    { id: 24, prefecture_id: 9, search_name: '宇都宮市文化,宇都宮文化', name: '宇都宮市文化会館' },
    { id: 25, prefecture_id: 9, search_name: '小山市立文化,小山市文化,小山文化', name: '小山市立文化センター' },
    { id: 26, prefecture_id: 9, search_name: '鹿沼市民文化,鹿沼市市民文化', name: '鹿沼市民文化センター' },
    { id: 27, prefecture_id: 9, search_name: '栃木県総合文化,栃木総合文化', name: '栃木県総合文化センター' },
    { id: 28, prefecture_id: 9, search_name: '栃木文化会館', name: '栃木文化会館' },
    { id: 29, prefecture_id: 9, search_name: '那須野が原,那須野ヶ原', name: '那須野が原ハーモニーホール' },
    { id: 30, prefecture_id: 9, search_name: '西方音楽館,木洩れ陽', name: '西方音楽館　木洩れ陽ホール' },
    { id: 31, prefecture_id: 9, search_name: '野木文化,野木町文化,エニス', name: '野木町文化会館・エニスホール' },
    { id: 32, prefecture_id: 10, search_name: '伊勢崎市文化,伊勢崎市文', name: '伊勢崎市文化会館' },
    { id: 33, prefecture_id: 10, search_name: '新田文化会館,エアリスホール', name: '太田市新田文化会館 エアリスホール' },
    { id: 34, prefecture_id: 10, search_name: '笠懸野文化,PAL,ＰＡＬ,pal,Pal', name: '笠懸野文化ホール・ＰＡＬ' },
    { id: 35, prefecture_id: 10, search_name: '桐生市市民文化,桐生市民文化', name: '桐生市市民文化会館' },
    { id: 36, prefecture_id: 10, search_name: '高崎シティ,高崎市シティ', name: '高崎シティギャラリー' },
    { id: 37, prefecture_id: 10, search_name: '玉村町文化,玉村文化', name: '玉村町文化センター' },
    { id: 38, prefecture_id: 10, search_name: '前橋市市民,前橋市民,大胡分館,シャンテ', name: '前橋市民文化会館大胡分館・シャンテ' },
    { id: 39, prefecture_id: 10, search_name: 'みかぼみらい館,みかぼ未来館', name: 'みかぼみらい館' },
    { id: 40, prefecture_id: 10, search_name: 'みなかみ町観光', name: 'みなかみ町観光会館' },
    { id: 41, prefecture_id: 11, search_name: '朝霞市市民,朝霞市民,ゆめぱれす', name: '朝霞市民会館・ゆめぱれす' },
    { id: 42, prefecture_id: 11, search_name: '入間市市民,入間市民', name: '入間市市民会館' },
    { id: 43, prefecture_id: 11, search_name: 'ウェスタ川越', name: 'ウェスタ川越' },
    { id: 44, prefecture_id: 11, search_name: '春日部市民,春日部市市民', name: '春日部市民文化会館' },
    { id: 45, prefecture_id: 11, search_name: '川口市総合文化,川口総合文化,リリア', name: '川口総合文化センター リリア' },
    { id: 46, prefecture_id: 11, search_name: '川越総合福祉,川越市総合福祉,エポックなかはら,エポック中原', name: '川越市総合福祉センター エポックなかはら(中原)' },
    { id: 47, prefecture_id: 11, search_name: '芝市民ホール', name: '川口市立芝市民ホール' },
    { id: 48, prefecture_id: 11, search_name: '久喜総合,久喜市総合', name: '久喜総合文化会館' },
    { id: 49, prefecture_id: 11, search_name: '久保稲荷公民館', name: '久保稲荷公民館' },
    { id: 50, prefecture_id: 11, search_name: '越谷コミュニティ,サンシティ', name: '越谷コミュニティセンター・サンシティホール' },
    { id: 51, prefecture_id: 11, search_name: '小手指公民館', name: '小手指公民館分館ホール' },
    { id: 52, prefecture_id: 11, search_name: 'さいたま市文化,さいたま文化', name: 'さいたま市文化センター' },
    { id: 53, prefecture_id: 11, search_name: 'さいたま芸術劇場,埼玉芸術劇場', name: '彩の国さいたま芸術劇場' },
    { id: 54, prefecture_id: 11, search_name: '埼玉会館', name: '埼玉会館' },
    { id: 55, prefecture_id: 11, search_name: '狭山市市民,狭山市民', name: '狭山市市民会館' },
    { id: 56, prefecture_id: 11, search_name: '鴻巣文化,鴻巣市文化,クレアこうのす,クレア鴻巣', name: '鴻巣市文化センター・クレアこうのす' },
    { id: 57, prefecture_id: 11, search_name: '草加市中央,草加市立中央', name: '草加市立中央公民館' },
    { id: 58, prefecture_id: 11, search_name: '草加市立中央,草加市中央,草加中央', name: '草加市立中央公民館' },
    { id: 59, prefecture_id: 11, search_name: '秩父宮記念,フォレスタ', name: '秩父宮記念市民会館大ホール フォレスタ' },
    { id: 60, prefecture_id: 11, search_name: '所沢文化,所沢市民文化,ミューズ', name: '所沢市民文化センター ミューズ' },
    { id: 61, prefecture_id: 11, search_name: '蓮田総合,蓮田市総合,ハストピア', name: '蓮田市総合文化会館ハストピア' },
    { id: 62, prefecture_id: 11, search_name: '羽生市産業文化,羽生産業文化', name: '羽生市産業文化ホール' },
    { id: 63, prefecture_id: 11, search_name: '富士見市市民,富士見市民,キラリふじみ,キラリ富士見', name: '富士見市民文化会館・キラリふじみ' },
    { id: 64, prefecture_id: 11, search_name: 'ふじみ野市勤労,ふじみ野勤労', name: 'ふじみ野市勤労福祉センター' },
    { id: 65, prefecture_id: 11, search_name: '富士見公民館', name: '富士見公民館' },
    { id: 66, prefecture_id: 11, search_name: 'ふるさと新座館', name: 'ふるさと新座館ホール' },
    { id: 67, prefecture_id: 11, search_name: '和光市市民,和光市民,アゼリア', name: '和光市民文化センター サン・アゼリア' },
    { id: 68, prefecture_id: 11, search_name: '蕨市市民,蕨市民,コンクレレ', name: '蕨市民会館コンクレレホール' },
    { id: 69, prefecture_id: 11, search_name: '蕨文化,蕨市文化,蕨市立文化,くるる', name: '蕨市立文化ホール くるる' },
    { id: 70, prefecture_id: 12, search_name: '青葉の森', name: '青葉の森公園芸術文化ホール' },
    { id: 71, prefecture_id: 12, search_name: 'アミュゼ柏', name: 'アミュゼ柏' },
    { id: 72, prefecture_id: 12, search_name: '市原市市民,市原市民', name: '市原市市民会館' },
    { id: 73, prefecture_id: 12, search_name: '市川市市民,市川市民', name: '市川市市民会館' },
    { id: 74, prefecture_id: 12, search_name: '市川市文化,市川文化', name: '市川市文化会館' },
    { id: 75, prefecture_id: 12, search_name: '市川男女共同,市川市男女共同,ウィズ', name: '市川市男女共同参画センター ウィズ' },
    { id: 76, prefecture_id: 12, search_name: '印西市文化,印西文化', name: '印西市文化ホール' },
    { id: 77, prefecture_id: 12, search_name: '浦安市文化,浦安文化', name: '浦安市文化会館' },
    { id: 78, prefecture_id: 12, search_name: '浦安音楽ホール', name: '浦安音楽ホール' },
    { id: 79, prefecture_id: 12, search_name: '海神公民館', name: '海神公民館' },
    { id: 80, prefecture_id: 12, search_name: '柏市民文化,柏市市民文化', name: '柏市民文化会館' },
    { id: 81, prefecture_id: 12, search_name: '行徳文化', name: '行徳文化ホール I&I' },
    { id: 82, prefecture_id: 12, search_name: '京葉銀行文化', name: '京葉銀行文化プラザ' },
    { id: 83, prefecture_id: 12, search_name: 'けやきプラザ', name: 'けやきプラザ' },
    { id: 84, prefecture_id: 12, search_name: '佐倉市民,佐倉市市民', name: '佐倉市民音楽ホール' },
    { id: 85, prefecture_id: 12, search_name: '沼南近隣センター,ひまわりプラザ', name: '沼南近隣センター ひまわりプラザ' },
    { id: 86, prefecture_id: 12, search_name: '白井市文化,白井文化', name: '白井市文化会館' },
    { id: 87, prefecture_id: 12, search_name: '白井文化,白井市文化,なし坊ホール', name: '白井市文化会館大 なし坊ホール' },
    { id: 88, prefecture_id: 12, search_name: '大栄公民館', name: '大栄公民館' },
    { id: 89, prefecture_id: 12, search_name: '東総文化', name: '千葉県東総文化会館' },
    { id: 90, prefecture_id: 12, search_name: '千葉県文化会館', name: '千葉県文化会館' },
    { id: 91, prefecture_id: 12, search_name: '千葉市民会館', name: '千葉市民会館' },
    { id: 92, prefecture_id: 12, search_name: '千葉市生涯,千葉生涯', name: '千葉市生涯学習センター' },
    { id: 93, prefecture_id: 12, search_name: '美浜文化', name: '千葉市美浜文化ホール' },
    { id: 94, prefecture_id: 12, search_name: '流山市文化,流山文化', name: '流山市文化会館' },
    { id: 95, prefecture_id: 12, search_name: '習志野文化,習志野市文化', name: '習志野文化ホール' },
    { id: 96, prefecture_id: 12, search_name: '西白井複合', name: '西白井複合センター' },
    { id: 97, prefecture_id: 12, search_name: '船橋市民,船橋市市民', name: '船橋市民文化ホール' },
    { id: 98, prefecture_id: 12, search_name: '葛飾公民館,葛飾区公民館', name: '船橋市葛飾公民館講堂' },
    { id: 99, prefecture_id: 12, search_name: '松戸文化,松戸市文化,森のホール', name: '松戸市文化会館 森のホール２１' },
    { id: 100, prefecture_id: 12, search_name: '宮本公民館', name: '宮本公民館' },
    { id: 101, prefecture_id: 12, search_name: '茂原市民,茂原市市民', name: '茂原市民会館' },
    { id: 102, prefecture_id: 12, search_name: '八千代市市民,八千代市民', name: '八千代市市民会館' },
    { id: 103, prefecture_id: 12, search_name: '山崎製パン,LLC,llc,Llc,ＬＬＣ', name: '山崎製パン総合クリエイションセンター 飯島藤十郎社主記念LLCホール' },
    { id: 104, prefecture_id: 12, search_name: '四街道市文化,四街道文化', name: '四街道市文化センター' },
    { id: 105, prefecture_id: 13, search_name: 'ＢＵＮＫＡ,bunka,BUNKA,Bunka,オーチャード', name: 'Bunkamura オーチャードホール' },
    { id: 106, prefecture_id: 13, search_name: 'アスピア', name: 'MY SPACE ASPIA アスピアホール' },
    { id: 107, prefecture_id: 13, search_name: 'SONORIUM,sonorium,ソノリウム', name: 'sonorium ソノリウム' },
    { id: 108, prefecture_id: 13, search_name: 'キララ', name: '秋川キララホール' },
    { id: 109, prefecture_id: 13, search_name: 'アコスタディオ', name: 'アコスタディオ' },
    { id: 110, prefecture_id: 13, search_name: '浅草公会堂,浅草区公会堂', name: '浅草公会堂' },
    { id: 111, prefecture_id: 13, search_name: '麻布区民', name: '麻布区民センター' },
    { id: 112, prefecture_id: 13, search_name: '石橋メモリアル', name: '石橋メモリアルホール' },
    { id: 113, prefecture_id: 13, search_name: '板橋区立文化,板橋区文化,板橋文化', name: '板橋区立文化会館' },
    { id: 114, prefecture_id: 13, search_name: '稲城市中央,稲城中央,稲城市立中央', name: '稲城市中央文化センター' },
    { id: 115, prefecture_id: 13, search_name: 'ⅰプラザ,iプラザ,Iプラザ,アイプラザ', name: '稲城市立ⅰプラザ' },
    { id: 116, prefecture_id: 13, search_name: '箪笥区民,箪笥区区民', name: '牛込箪笥区民ホール' },
    { id: 117, prefecture_id: 13, search_name: '江戸川区総合文化,江戸川総合文化', name: '江戸川区総合文化センター' },
    { id: 118, prefecture_id: 13, search_name: '絵本塾ホール', name: '絵本塾ホール' },
    { id: 119, prefecture_id: 13, search_name: '王子ホール', name: '王子ホール' },
    { id: 120, prefecture_id: 13, search_name: '近江楽堂', name: '近江楽堂' },
    { id: 121, prefecture_id: 13, search_name: '太田区民ホール,アプリコ', name: '太田区民ホール／アプリコ' },
    { id: 122, prefecture_id: 13, search_name: '大泉学園,ゆめりあ', name: '大泉学園ゆめりあホール' },
    { id: 123, prefecture_id: 13, search_name: '大田区民プラザ', name: '大田区民プラザ' },
    { id: 124, prefecture_id: 13, search_name: '大田区民センター,大田区区民センター', name: '大田区民センター' },
    { id: 125, prefecture_id: 13, search_name: '大田文化の森', name: '大田文化の森' },
    { id: 126, prefecture_id: 13, search_name: 'オーキッド', name: 'オーキッドミュージックサロン' },
    { id: 127, prefecture_id: 13, search_name: 'オリンパス', name: 'オリンパスホール八王子' },
    { id: 128, prefecture_id: 13, search_name: '音楽の友', name: '音楽の友ホール' },
    { id: 129, prefecture_id: 13, search_name: 'かつしかシンフォニー,葛飾シンフォニー', name: 'かつしかシンフォニーヒルズ' },
    { id: 130, prefecture_id: 13, search_name: 'ガルバホール', name: 'ガルバホール' },
    { id: 131, prefecture_id: 13, search_name: 'カワイ表参道,パウゼ', name: 'カワイ表参道　コンサートホール「パウゼ」' },
    { id: 132, prefecture_id: 13, search_name: '川崎男女,川崎市男女,すくらむ21', name: '川崎市男女共同参画センター (すくらむ21)' },
    { id: 133, prefecture_id: 13, search_name: '紀尾井', name: '紀尾井ホール' },
    { id: 134, prefecture_id: 13, search_name: '北とぴあ,北トピア', name: '北とぴあ' },
    { id: 135, prefecture_id: 13, search_name: 'ギャラクシティ,西新井文化,西新井市文化', name: 'ギャラクシティ西新井文化ホール' },
    { id: 136, prefecture_id: 13, search_name: '清瀬けやき', name: '清瀬けやきホール' },
    { id: 137, prefecture_id: 13, search_name: 'ブロッサム', name: '銀座ブロッサム中央会館' },
    { id: 138, prefecture_id: 13, search_name: 'くにたち市民,くにたち市市民', name: 'くにたち市民芸術小ホール' },
    { id: 139, prefecture_id: 13, search_name: 'アーバンプラザ', name: '小岩アーバンプラザ' },
    { id: 140, prefecture_id: 13, search_name: '江東区文化,江東文化', name: '江東区文化センター' },
    { id: 141, prefecture_id: 13, search_name: '江東区公会堂,江東公会堂,ティアラこうとう,ティアラ江東', name: '江東公会堂 ティアラこうとう' },
    { id: 142, prefecture_id: 13, search_name: 'コール田無', name: 'コール田無' },
    { id: 143, prefecture_id: 13, search_name: '宮地楽器', name: '小金井 宮地楽器ホール' },
    { id: 144, prefecture_id: 13, search_name: 'オリンピック', name: '国立オリンピック記念青少年総合センター' },
    { id: 145, prefecture_id: 13, search_name: '五反田文化', name: '五反田文化センター' },
    { id: 146, prefecture_id: 13, search_name: 'エコルマ', name: '狛江エコルマホール' },
    { id: 147, prefecture_id: 13, search_name: 'サローネ,Salone,SALONE,salone', name: 'サローネフォンタナ (Salone Fontan)' },
    { id: 148, prefecture_id: 13, search_name: 'テッセラ', name: 'サロン・テッセラ' },
    { id: 149, prefecture_id: 13, search_name: 'サントリーホール', name: 'サントリーホール' },
    { id: 150, prefecture_id: 13, search_name: 'サンパール荒川,荒川区民,荒川区区民', name: 'サンパール荒川 荒川区民会館' },
    { id: 151, prefecture_id: 13, search_name: 'ＪＴ,JT,アフィニス', name: 'JTアートホールアフィニス' },
    { id: 152, prefecture_id: 13, search_name: '品川区総合,きゅりあん', name: '品川区総合区民会館　 きゅりあん' },
    { id: 153, prefecture_id: 13, search_name: '芝浦港南区', name: '芝浦港南区民センター' },
    { id: 154, prefecture_id: 13, search_name: '渋谷区文化総合センター,大和田', name: '渋谷区文化総合センター大和田' },
    { id: 155, prefecture_id: 13, search_name: '昭島市民,KOTORI,kotori,ＫＯＴＯＲＩ,Kotori,ことり,コトリ', name: '昭島市民会館　KOTORIホール' },
    { id: 156, prefecture_id: 13, search_name: '昭和女子大,人見記念', name: '昭和女子大学人見記念講堂' },
    { id: 157, prefecture_id: 13, search_name: '松濤', name: '松濤サロン' },
    { id: 158, prefecture_id: 13, search_name: 'アイム', name: '女性総合センター・アイム' },
    { id: 159, prefecture_id: 13, search_name: '新宿文化センター,新宿区文化センター', name: '新宿区立新宿文化センター' },
    { id: 160, prefecture_id: 13, search_name: 'シンフォニーサロン', name: 'シンフォニーサロン (Symphony Salon)' },
    { id: 161, prefecture_id: 13, search_name: '杉並公会堂', name: '杉並公会堂' },
    { id: 162, prefecture_id: 13, search_name: 'スクエア荏原', name: 'スクエア荏原' },
    { id: 163, prefecture_id: 13, search_name: 'スタインウェイサロン東京', name: 'スタインウェイサロン東京' },
    { id: 164, prefecture_id: 13, search_name: 'スペースDo,スペースドゥ,スペース・ドゥ', name: 'スペースDo' },
    { id: 165, prefecture_id: 13, search_name: 'すみだトリフォニー,墨田トリフォニー', name: 'すみだトリフォニーホール' },
    { id: 166, prefecture_id: 13, search_name: '曳舟文化,曳舟市文化', name: '墨田区曳舟文化センター' },
    { id: 167, prefecture_id: 13, search_name: '成城ホール', name: '成城ホール' },
    { id: 168, prefecture_id: 13, search_name: '西東京市市民,西東京市民', name: '西東京市市民会館' },
    { id: 169, prefecture_id: 13, search_name: '保谷こもれび,保谷木漏れ日', name: '西東京市保谷こもれびホール' },
    { id: 170, prefecture_id: 13, search_name: 'セシオン杉並', name: 'セシオン杉並' },
    { id: 171, prefecture_id: 13, search_name: '世田谷区民,世田谷区区民', name: '世田谷区民会館' },
    { id: 172, prefecture_id: 13, search_name: '第一生命ホール', name: '第一生命ホール' },
    { id: 173, prefecture_id: 13, search_name: '台東生涯,台東区生涯,ミレニアムホール', name: '台東区生涯学習センター ミレニアムホール' },
    { id: 174, prefecture_id: 13, search_name: '高井戸地域区民センター', name: '高井戸地域区民センター' },
    { id: 175, prefecture_id: 13, search_name: 'プリンセスガルテン', name: '高輪プリンセスガルテン' },
    { id: 176, prefecture_id: 13, search_name: '滝野川会館', name: '滝野川会館' },
    { id: 177, prefecture_id: 13, search_name: '立川市市民,立川市民,アミュー立川', name: '立川市市民会館 アミュー立川' },
    { id: 178, prefecture_id: 13, search_name: '立川市民,立川市市民,たましん', name: '立川市市民会館 たましんRISURUホール' },
    { id: 179, prefecture_id: 13, search_name: '関戸公民館,VITA,Vita,vita,ヴィータ', name: '多摩市立関戸公民館 VITAホール(ヴィータホール)' },
    { id: 180, prefecture_id: 13, search_name: 'タワーホール', name: 'タワーホール船堀' },
    { id: 181, prefecture_id: 13, search_name: '日本橋公会堂,日本橋劇場', name: '中央区立日本橋公会堂／日本橋劇場' },
    { id: 182, prefecture_id: 13, search_name: '内幸町ホール', name: '千代田区立内幸町ホール' },
    { id: 183, prefecture_id: 13, search_name: '調布グリーン,調布市グリーン', name: '調布グリーン・ホール' },
    { id: 184, prefecture_id: 13, search_name: '調布市文化会館,調布文化会館', name: '調布市文化会館たづくり' },
    { id: 185, prefecture_id: 13, search_name: '角筈区民ホール,角筈ホール', name: '角筈区民ホール' },
    { id: 186, prefecture_id: 13, search_name: 'オペラシティ', name: '東京オペラシティ' },
    { id: 187, prefecture_id: 13, search_name: '東京カテドラル,聖マリア大聖堂', name: '東京カテドラル聖マリア大聖堂' },
    { id: 188, prefecture_id: 13, search_name: '東京芸術劇場', name: '東京芸術劇場' },
    { id: 189, prefecture_id: 13, search_name: '東京文化会館', name: '東京文化会館' },
    { id: 190, prefecture_id: 13, search_name: '東部フレンド', name: '東部フレンドホール' },
    { id: 191, prefecture_id: 13, search_name: 'としまセンター,としまスクウェア,豊島センター,豊島スクウェア', name: 'としまセンタースクエア' },
    { id: 192, prefecture_id: 13, search_name: 'トッパン,凸版', name: 'トッパンホール' },
    { id: 193, prefecture_id: 13, search_name: '豊洲文化,豊洲シビック', name: '豊洲文化センター 豊洲シビックセンター' },
    { id: 194, prefecture_id: 13, search_name: 'ＺＥＲＯ,Zero,zero,ZERO,もみじ山文化', name: 'なかのZero（中野区もみじ山文化センター）' },
    { id: 195, prefecture_id: 13, search_name: 'ＺＥＲＯ,ZERO,Zero,zero', name: 'なかのZERO' },
    { id: 196, prefecture_id: 13, search_name: '日暮里サニー', name: '日暮里サニーホール' },
    { id: 197, prefecture_id: 13, search_name: '練馬文化センター', name: '練馬文化センター' },
    { id: 198, prefecture_id: 13, search_name: '関区民,関区区民', name: '練馬区関区民ホール' },
    { id: 199, prefecture_id: 13, search_name: '練馬区生涯,練馬生涯', name: '練馬区生涯学習センター' },
    { id: 200, prefecture_id: 13, search_name: '野方区民,野方区区民', name: '野方区民ホール' },
    { id: 201, prefecture_id: 13, search_name: '八王子市芸術,八王子芸術,いちょうホール,イチョウホール', name: '八王子市芸術文化会館 いちょうホール' },
    { id: 202, prefecture_id: 13, search_name: '南大沢文化', name: '八王子市南大沢文化会館' },
    { id: 203, prefecture_id: 13, search_name: '八王子市立芸術,八王子芸術,八王子市芸術,いちょうホール', name: '八王子市芸術文化会館 いちょうホール' },
    { id: 204, prefecture_id: 13, search_name: '浜離宮', name: '浜離宮朝日ホール' },
    { id: 205, prefecture_id: 13, search_name: '羽村生涯,羽村市生涯,ゆとろぎ', name: '羽村市生涯学習センター　ゆとろぎ' },
    { id: 206, prefecture_id: 13, search_name: 'パルテノン', name: 'パルテノン多摩' },
    { id: 207, prefecture_id: 13, search_name: 'IMA,ima,イマホール', name: '光が丘IMA (IMA HALL)' },
    { id: 208, prefecture_id: 13, search_name: '東大和市市民会館,東大和市民会館,ハミング', name: '東大和市民会館ハミングホール' },
    { id: 209, prefecture_id: 13, search_name: 'ひの煉瓦,日野市民m日野市市民', name: 'ひの煉瓦ホール(日野市民会館)' },
    { id: 210, prefecture_id: 13, search_name: '江戸資料館,深川資料館', name: '深川江戸資料館' },
    { id: 211, prefecture_id: 13, search_name: '府中の森', name: '府中の森芸術劇場' },
    { id: 212, prefecture_id: 13, search_name: '府中市民,府中市市民,バルトホール', name: '府中市市民センター バルトホール' },
    { id: 213, prefecture_id: 13, search_name: '福生市民,福生市市民', name: '福生市民会館' },
    { id: 214, prefecture_id: 13, search_name: '古石場文化センター', name: '古石場文化センター' },
    { id: 215, prefecture_id: 13, search_name: 'シビック', name: '文京シビックホール' },
    { id: 216, prefecture_id: 13, search_name: '町田市民,町田市市民', name: '町田市民ホール' },
    { id: 217, prefecture_id: 13, search_name: '松本記念', name: '松本記念音楽迎賓館' },
    { id: 218, prefecture_id: 13, search_name: 'まろにえホール,東久留米市立生涯,東久留米市生涯,,東久留米生涯', name: 'まろにえホール 東久留米市立生涯学習センター' },
    { id: 219, prefecture_id: 13, search_name: '三鷹市芸術,三鷹芸術', name: '三鷹市芸術文化センター' },
    { id: 220, prefecture_id: 13, search_name: '三鷹市公会堂,三鷹公会堂', name: '三鷹市公会堂' },
    { id: 221, prefecture_id: 13, search_name: 'メイズ,ＭＡＹＳ,MAYS,Mays,mays', name: 'ミュージックスタジオメイズ (music studio MAYS)' },
    { id: 222, prefecture_id: 13, search_name: '村山市市民,村山市民,さくらホール', name: '武蔵村山市民会館（さくらホール）' },
    { id: 223, prefecture_id: 13, search_name: '武蔵野公会堂', name: '武蔵野公会堂' },
    { id: 224, prefecture_id: 13, search_name: '武蔵野市民文化,武蔵野市市民文化,武蔵野文化', name: '武蔵野市民文化会館' },
    { id: 225, prefecture_id: 13, search_name: 'ムジカーザ', name: 'ムジカーザ' },
    { id: 226, prefecture_id: 13, search_name: 'パーシモン', name: 'めぐろパーシモンホール' },
    { id: 227, prefecture_id: 13, search_name: 'メルパルク', name: 'メルパルクホールTOKYO' },
    { id: 228, prefecture_id: 13, search_name: 'やなか音楽,谷中音楽', name: 'やなか音楽ホール' },
    { id: 229, prefecture_id: 13, search_name: 'ヤマハホール', name: 'ヤマハホール' },
    { id: 230, prefecture_id: 13, search_name: '四谷区民,四谷区区民', name: '四谷区民ホール' },
    { id: 231, prefecture_id: 13, search_name: '代々木の森,リブロ,LIBRO,Libro,libro', name: '代々木の森 リブロホール(LIBRO Hall)' },
    { id: 232, prefecture_id: 13, search_name: 'ルーテル', name: 'ルーテル市ヶ谷センター' },
    { id: 233, prefecture_id: 13, search_name: 'ルネこだいら,ルネ小平,小平市民,小平市市民', name: 'ルネこだいら／小平市民文化会館' },
    { id: 234, prefecture_id: 13, search_name: 'Ｋコンサート,kコンサート,Kコンサート', name: '六本木Ｋコンサートサロン' },
    { id: 235, prefecture_id: 14, search_name: '青葉文化,青葉区文化,青葉区民,フィリア', name: '青葉区民文化センター・フィリアホール' },
    { id: 236, prefecture_id: 14, search_name: '青葉公会堂', name: '青葉公会堂' },
    { id: 237, prefecture_id: 14, search_name: '旭区区民文化,旭区民文化,サンハート', name: '旭区民文化センター・サンハート' },
    { id: 238, prefecture_id: 14, search_name: '厚木市文化,厚木市市文化', name: '厚木市文化会館' },
    { id: 239, prefecture_id: 14, search_name: 'アミュー厚木,アミューあつぎ', name: 'アミュー厚木 アミューあつぎ' },
    { id: 240, prefecture_id: 14, search_name: '伊勢原市民,伊勢原市市民', name: '伊勢原市民文化会館' },
    { id: 241, prefecture_id: 14, search_name: '磯子文化,磯子区文化,磯子区民文化,杉田劇場', name: '磯子区民文化センター 杉田劇場' },
    { id: 242, prefecture_id: 14, search_name: '磯子公会堂', name: '磯子公会堂' },
    { id: 243, prefecture_id: 14, search_name: '岩崎博物館,ゲーテ座', name: '岩崎博物館 山手ゲーテ座' },
    { id: 244, prefecture_id: 14, search_name: '海老名市文化,海老名市市文化', name: '海老名市文化会館' },
    { id: 245, prefecture_id: 14, search_name: '海老名文化', name: '海老名文化会館' },
    { id: 246, prefecture_id: 14, search_name: '小田原市民,小田原市市民', name: '小田原市民会館' },
    { id: 247, prefecture_id: 14, search_name: '神奈川県立音楽,神奈川音楽,神奈川県音楽', name: '神奈川県立音楽堂' },
    { id: 248, prefecture_id: 14, search_name: '神奈川県立県民,神奈川県民', name: '神奈川県立県民ホール' },
    { id: 249, prefecture_id: 14, search_name: '神奈川区民文化,神奈川県区民文化,かなっく', name: '神奈川県区民文化センター かなっくホール' },
    { id: 250, prefecture_id: 14, search_name: '相模湖交流', name: '神奈川県立相模湖交流センター' },
    { id: 251, prefecture_id: 14, search_name: '鎌倉芸術館', name: '鎌倉芸術館' },
    { id: 252, prefecture_id: 14, search_name: '上笹下地域ケアプラザ,上笹下ケアプラザ', name: '上笹下地域ケアプラザ' },
    { id: 253, prefecture_id: 14, search_name: '宮前市民館,宮前市市民館', name: '川崎市宮前市民館' },
    { id: 254, prefecture_id: 14, search_name: '川崎市教育文化,川崎教育文化', name: '川崎市教育文化会館' },
    { id: 255, prefecture_id: 14, search_name: '麻生市民,麻生市市民', name: '川崎市麻生市民館' },
    { id: 256, prefecture_id: 14, search_name: '幸市民館,幸市市民館', name: '川崎市幸市民館' },
    { id: 257, prefecture_id: 14, search_name: '多摩市民館,多摩市市民館', name: '川崎市多摩市民館' },
    { id: 258, prefecture_id: 14, search_name: '協生館,藤原洋記念ホール', name: '協生館 藤原洋記念ホール' },
    { id: 259, prefecture_id: 14, search_name: 'エールさがみはら,エール相模原', name: 'サン・エールさがみはら' },
    { id: 260, prefecture_id: 14, search_name: '逗子文化,逗子市文化', name: '逗子文化プラザ' },
    { id: 261, prefecture_id: 14, search_name: '関内ホール,横浜市市民,横浜市民', name: '関内ホール・横浜市市民文化会館' },
    { id: 262, prefecture_id: 14, search_name: '相馬女子,相馬大学', name: '相模女子大学グリーンホール' },
    { id: 263, prefecture_id: 14, search_name: '相模原市民,相模原市市民', name: '相模原市民会館' },
    { id: 264, prefecture_id: 14, search_name: 'タウンニュース', name: 'タウンニュースホール' },
    { id: 265, prefecture_id: 14, search_name: '高津市市民,高津市民,ノクティ', name: '高津市民館 ノクティホール' },
    { id: 266, prefecture_id: 14, search_name: '茅ヶ崎市民,茅ヶ崎市市民', name: '茅ヶ崎市民文化会館' },
    { id: 267, prefecture_id: 14, search_name: '都筑公会堂', name: '都筑公会堂' },
    { id: 268, prefecture_id: 14, search_name: '鶴見区区民,鶴見区民,サルビア', name: '鶴見区民文化センター サルビアホール' },
    { id: 269, prefecture_id: 14, search_name: '桐蔭学園', name: '桐蔭学園シンフォニーホール' },
    { id: 270, prefecture_id: 14, search_name: '戸塚文化,戸塚区文化,戸塚区民文化,さくらプラザ', name: '戸塚区民文化センター さくらプラザ' },
    { id: 271, prefecture_id: 14, search_name: '二宮生涯,二宮町生涯,ラディアン', name: '二宮町生涯学習センター・ラディアン' },
    { id: 272, prefecture_id: 14, search_name: 'ハーモニーホール座間', name: 'ハーモニーホール座間' },
    { id: 273, prefecture_id: 14, search_name: 'ハウスクエア横浜,ハウススクエア横浜', name: 'ハウスクエア横浜' },
    { id: 274, prefecture_id: 14, search_name: '仙石原文化,仙石原市文化', name: '箱根町仙石原文化センター' },
    { id: 275, prefecture_id: 14, search_name: '秦野市文化,秦野文化', name: '秦野市文化会館' },
    { id: 276, prefecture_id: 14, search_name: '平塚市中央,平塚中央', name: '平塚市中央公民館' },
    { id: 277, prefecture_id: 14, search_name: '藤沢市民,藤沢市市民', name: '藤沢市民会館' },
    { id: 278, prefecture_id: 14, search_name: 'ブラフ18,ブラフ１８', name: 'ブラフ18番館' },
    { id: 279, prefecture_id: 14, search_name: '港北公会堂', name: '港北公会堂' },
    { id: 280, prefecture_id: 14, search_name: 'ミューザ川崎', name: 'ミューザ川崎シンフォニーホール' },
    { id: 281, prefecture_id: 14, search_name: '杜のホール,はしもと', name: '杜のホールはしもと' },
    { id: 282, prefecture_id: 14, search_name: '文化創造拠点,シリウス,芸術文化ホール', name: '大和市文化創造拠点シリウス 芸術文化ホール' },
    { id: 283, prefecture_id: 14, search_name: '横須賀芸術,よこすか芸術,ヨコスカ芸術', name: '横須賀芸術劇場' },
    { id: 284, prefecture_id: 14, search_name: 'みなとみらい', name: '横浜みなとみらいホール' },
    { id: 285, prefecture_id: 14, search_name: '栄区区民文化,栄区民文化,リリス', name: '横浜市栄区民文化センター・リリス' },
    { id: 286, prefecture_id: 14, search_name: '港南区区民文化,港南区民文化,ひまわりの郷', name: '横浜市港南区民文化センター・ひまわりの郷' },
    { id: 287, prefecture_id: 14, search_name: 'ベイサイド', name: 'ヨコスカ・ベイサイド・ポケット' },
    { id: 288, prefecture_id: 14, search_name: '横須賀芸術劇場', name: '横須賀芸術劇場' },
    { id: 289, prefecture_id: 14, search_name: '大さん橋', name: '横浜港 大さん橋 国際旅客ターミナル' },
    { id: 290, prefecture_id: 14, search_name: '都筑公会堂', name: '横浜市 都筑公会堂' },
    { id: 291, prefecture_id: 14, search_name: '栄公会堂', name: '横浜市栄公会堂' },
    { id: 292, prefecture_id: 14, search_name: '開港記念会館', name: '横浜市開港記念会館' },
    { id: 293, prefecture_id: 14, search_name: '西公会堂', name: '横浜市西公会堂' },
    { id: 294, prefecture_id: 14, search_name: '泉公会堂', name: '横浜市泉公会堂' },
    { id: 295, prefecture_id: 14, search_name: '南公会堂', name: '横浜市南公会堂' },
    { id: 296, prefecture_id: 14, search_name: '六浦地域ケアプラザ,六浦ケアプラザ', name: '横浜市六浦地域ケアプラザ' },
    { id: 297, prefecture_id: 15, search_name: '上越文化,上越市文化', name: '上越文化会館' },
    { id: 298, prefecture_id: 15, search_name: 'だいし', name: 'だいしホール' },
    { id: 299, prefecture_id: 15, search_name: 'リリック', name: '長岡リリックホール' },
    { id: 300, prefecture_id: 15, search_name: '新潟市音楽,新潟音楽', name: '新潟市音楽文化会館' },
    { id: 301, prefecture_id: 15, search_name: '新潟市北区,新潟北区', name: '新潟市北区文化会館' },
    { id: 302, prefecture_id: 16, search_name: '北日本新聞', name: '北日本新聞ホール' },
    { id: 303, prefecture_id: 16, search_name: '婦中ふれあい', name: '富山市婦中ふれあい館' },
    { id: 304, prefecture_id: 17, search_name: '石川県立音楽堂,石川県音楽堂,石川音楽堂', name: '石川県立音楽堂' },
    { id: 305, prefecture_id: 17, search_name: '金沢市文化,金沢文化', name: '金沢市文化ホール' },
    { id: 306, prefecture_id: 17, search_name: '小松市公会堂,小松公会堂', name: '小松市公会堂' },
    { id: 307, prefecture_id: 18, search_name: '福井音楽堂,福井県音楽堂,福井県立音楽堂,ハーモニーホールふくい,ハーモニーホール福井', name: '福井県立音楽堂・ハーモニーホールふくい' },
    { id: 308, prefecture_id: 19, search_name: '清里の森,森の音楽堂', name: '清里の森・森の音楽堂' },
    { id: 309, prefecture_id: 19, search_name: 'コラニー', name: 'コラニー文化ホール' },
    { id: 310, prefecture_id: 19, search_name: '高根ふれあい,八ヶ岳やまびこ', name: '高根ふれあい交流ホール 八ヶ岳やまびこホール' },
    { id: 311, prefecture_id: 19, search_name: 'スコレー', name: '笛吹市スコレーセンター' },
    { id: 312, prefecture_id: 19, search_name: '杜の都,うぐいすホール', name: '杜の都うぐいすホール' },
    { id: 313, prefecture_id: 20, search_name: 'あがたの森', name: 'あがたの森文化会館' },
    { id: 314, prefecture_id: 20, search_name: 'キッセイ,松本文化,松本市文化', name: 'キッセイ文化ホール・長野県松本文化会館' },
    { id: 315, prefecture_id: 20, search_name: '小海町音楽堂', name: '小海町音楽堂' },
    { id: 316, prefecture_id: 20, search_name: '塩尻文化,塩尻市文化,レザン', name: '塩尻市文化会館 レザンホール' },
    { id: 317, prefecture_id: 20, search_name: '須坂文化,須坂市文化,メセナ', name: '須坂市文化会館 メセナホール' },
    { id: 318, prefecture_id: 20, search_name: '更埴文化,あんず', name: '千曲市更埴文化会館・あんずホール' },
    { id: 319, prefecture_id: 20, search_name: '茅野市民,茅野市市民', name: '茅野市民館コンサートホール' },
    { id: 320, prefecture_id: 20, search_name: '長野文化,長野県県民文化,長野県民文化,ホクト文化,北斗文化,ほくと文化', name: '長野県県民文化会館・ホクト文化ホール' },
    { id: 321, prefecture_id: 20, search_name: '長野市芸術館,長野芸術館', name: '長野市芸術館' },
    { id: 322, prefecture_id: 20, search_name: '松代文化,松代市文化', name: '松代文化ホール' },
    { id: 323, prefecture_id: 21, search_name: 'サラマンカ', name: 'サラマンカホール' },
    { id: 324, prefecture_id: 21, search_name: '不二羽島文化', name: '不二羽島文化センター' },
    { id: 325, prefecture_id: 21, search_name: '本巣市民,本巣市市民', name: '本巣市民文化ホール' },
    { id: 326, prefecture_id: 22, search_name: 'アクトシティ', name: 'アクトシティ浜松' },
    { id: 327, prefecture_id: 22, search_name: '御殿場市民,御殿場市市民', name: '御殿場市民会館' },
    { id: 328, prefecture_id: 22, search_name: '清水町地域', name: '清水町地域交流センター' },
    { id: 329, prefecture_id: 22, search_name: '浜北文化,浜北市文化', name: '浜松市浜北文化センター' },
    { id: 330, prefecture_id: 22, search_name: '浜松市勤労,浜松勤労,浜松市立勤労', name: '浜松市勤労会館 Uホール' },
    { id: 331, prefecture_id: 22, search_name: '浜松市福祉,浜松市立福祉,浜松福祉', name: '浜松市福祉交流センター' },
    { id: 332, prefecture_id: 22, search_name: '三島市市民,三島市民,ゆうゆう', name: '三島市民文化会館・ゆうゆうホール' },
    { id: 333, prefecture_id: 23, search_name: '５/R,5/R,HALL,Hall,hall,ＨＡＬＬ', name: '５/R HALL&Gallery' },
    { id: 334, prefecture_id: 23, search_name: '愛知県芸術,愛知県立芸術', name: '愛知県芸術劇場' },
    { id: 335, prefecture_id: 23, search_name: 'ウィルあいち,ウィル愛知', name: '愛知県女性総合センター ウィルあいち' },
    { id: 336, prefecture_id: 23, search_name: '熱田文化小劇場', name: '熱田文化小劇場' },
    { id: 337, prefecture_id: 23, search_name: 'イーストプラザ,いこまい館', name: 'イーストプラザいこまい館' },
    { id: 338, prefecture_id: 23, search_name: '犬山市民,犬山市市民', name: '犬山市民文化会館' },
    { id: 339, prefecture_id: 23, search_name: '岡崎シビック,岡崎市シビック,コロネット', name: '岡崎市シビックセンター (コンサートホール コロネット)' },
    { id: 340, prefecture_id: 23, search_name: '尾張旭市文化,尾張旭文化,尾張旭市民文化', name: '尾張旭市文化会館' },
    { id: 341, prefecture_id: 23, search_name: '刈谷総合,刈谷市総合,アイリス', name: '刈谷市総合文化センター・アイリス' },
    { id: 342, prefecture_id: 23, search_name: '北名古屋市文化,北名古屋文化', name: '北名古屋市文化勤労会館' },
    { id: 343, prefecture_id: 23, search_name: '小牧市市民,小牧市民', name: '小牧市市民会館' },
    { id: 344, prefecture_id: 23, search_name: '知多勤労,知多市勤労', name: '知多市勤労文化会館' },
    { id: 345, prefecture_id: 23, search_name: '電気文化会館', name: '電気文化会館ザ・コンサートホール' },
    { id: 346, prefecture_id: 23, search_name: '東海市芸術,東海芸術', name: '東海市芸術劇場' },
    { id: 347, prefecture_id: 23, search_name: '豊田市コンサート,豊田市能楽堂,豊田能楽堂', name: '豊田市コンサートホール 豊田市能楽堂' },
    { id: 348, prefecture_id: 23, search_name: 'アートホールNagoya,アートホール名古屋,アートホールなごや', name: 'ドルチェ・アートホールNagoya' },
    { id: 349, prefecture_id: 23, search_name: '中川文化小劇場', name: '中川文化小劇場' },
    { id: 350, prefecture_id: 23, search_name: '長久手市文化,長久手文化,長久手市民文化', name: '長久手市文化の家' },
    { id: 351, prefecture_id: 23, search_name: '守山文化小劇場,守山市文化小劇場', name: '名古屋守山文化小劇場' },
    { id: 352, prefecture_id: 23, search_name: '名東文化小劇場,名東市文化小劇場', name: '名古屋名東文化小劇場' },
    { id: 353, prefecture_id: 23, search_name: '名古屋国際,センチュリーホール', name: '名古屋国際会議場　センチュリーホール' },
    { id: 354, prefecture_id: 23, search_name: '瑞穂文化小劇場', name: '名古屋市瑞穂文化小劇場' },
    { id: 355, prefecture_id: 23, search_name: '名古屋青少年,名古屋市青少年,アートピア', name: '名古屋市青少年文化センター アートピア' },
    { id: 356, prefecture_id: 23, search_name: '名古屋男女,名古屋市男女,イーブルなごや,イーブル名古屋', name: '名古屋市男女平等参画推進センター・女性会館 イーブルなごやホール' },
    { id: 357, prefecture_id: 23, search_name: '西尾市文化,西尾文化', name: '西尾市文化会館' },
    { id: 358, prefecture_id: 23, search_name: '陶業市民,陶業会館', name: '日本特殊陶業市民会館' },
    { id: 359, prefecture_id: 23, search_name: '穂の国,とよはし芸術劇場,プラット', name: '穂の国とよはし芸術劇場プラット' },
    { id: 360, prefecture_id: 23, search_name: 'しらかわホール,白河ホール,白川ホール,三井住友海上', name: '三井住友海上しらかわホール' },
    { id: 361, prefecture_id: 23, search_name: '港文化小劇場', name: '港文化小劇場' },
    { id: 362, prefecture_id: 23, search_name: 'ライフポート', name: 'ライフポートとよはし' },
    { id: 363, prefecture_id: 24, search_name: 'クラギ文化,蔵木文化', name: 'クラギ文化ホール' },
    { id: 364, prefecture_id: 24, search_name: '鈴鹿市民,鈴鹿市市民', name: '鈴鹿市民会館' },
    { id: 365, prefecture_id: 24, search_name: '津市アスト,アスト津', name: '津市アストプラザ アスト津' },
    { id: 366, prefecture_id: 25, search_name: '近江八幡市文化,近江八幡文化', name: '近江八幡市文化会館' },
    { id: 367, prefecture_id: 25, search_name: '滋賀県芸術,滋賀県立芸術,滋賀芸術,びわ湖ホール,琵琶湖ホール', name: '滋賀県立芸術劇場・びわ湖ホール' },
    { id: 368, prefecture_id: 25, search_name: '奏美ホール', name: '奏美ホール' },
    { id: 369, prefecture_id: 25, search_name: 'ひこね市文化,彦根市文化,ひこね文化', name: 'ひこね市文化プラザ' },
    { id: 370, prefecture_id: 25, search_name: '日野町町民,日野町民,わたむき', name: '日野町町民会館・わたむきホール虹' },
    { id: 371, prefecture_id: 25, search_name: '栗東芸術文化,さきら', name: '栗東芸術文化会館・さきら' },
    { id: 372, prefecture_id: 26, search_name: 'KOKOKA,kokoka,京都市国際交流,京都国際交流', name: 'kokoka京都市国際交流会館' },
    { id: 373, prefecture_id: 26, search_name: '青山音楽記念,バロックザール', name: '青山音楽記念館・バロックザール' },
    { id: 374, prefecture_id: 26, search_name: '宇治市文化,宇治文化', name: '宇治市文化会館' },
    { id: 375, prefecture_id: 26, search_name: '宇治文化,宇治市文化', name: '宇治文化センター' },
    { id: 376, prefecture_id: 26, search_name: '加茂文化,加茂町文化,あじさいホール', name: '加茂町文化センター・あじさいホール' },
    { id: 377, prefecture_id: 26, search_name: '京都コンサート', name: '京都コンサートホール' },
    { id: 378, prefecture_id: 26, search_name: '長岡京記念', name: '京都市長岡京記念文化会館' },
    { id: 379, prefecture_id: 26, search_name: '京都府民,京都府立府民,アルティ', name: '京都府立府民ホール・アルティ' },
    { id: 380, prefecture_id: 26, search_name: '京都府こども文化,京都こども文化,エンゼルハウス', name: '京都こども文化会館 (エンゼルハウス)' },
    { id: 381, prefecture_id: 26, search_name: '京都教育文化,京都府教育文化', name: '京都教育文化センター' },
    { id: 382, prefecture_id: 26, search_name: '京都文化博物館', name: '京都文化博物館' },
    { id: 383, prefecture_id: 26, search_name: 'パルク', name: '文化パルク城陽' },
    { id: 384, prefecture_id: 26, search_name: '八幡市文化,八幡文化', name: '八幡市文化センター' },
    { id: 385, prefecture_id: 26, search_name: 'ロームシアター', name: 'ロームシアター京都' },
    { id: 386, prefecture_id: 27, search_name: 'tech,Tech,TECH', name: 'B-tech Japan' },
    { id: 387, prefecture_id: 27, search_name: 'フェニックス,あいおいニッセイ', name: 'あいおいニッセイ同和損保 ザ・フェニックスホール' },
    { id: 388, prefecture_id: 27, search_name: '阿倍野区民,阿倍野区区民', name: '阿倍野区民センター' },
    { id: 389, prefecture_id: 27, search_name: 'いずみホール,泉ホール', name: 'いずみホール' },
    { id: 390, prefecture_id: 27, search_name: '茨木総合,茨木市総合,茨木市民総合,茨木市市民総合,クリエイトセンター', name: '茨木市市民総合センター (クリエイトセンター)' },
    { id: 391, prefecture_id: 27, search_name: '大阪国際', name: '大阪国際交流センター' },
    { id: 392, prefecture_id: 27, search_name: 'こども文化', name: '大阪市立こども文化センター' },
    { id: 393, prefecture_id: 27, search_name: '大阪フィル', name: '大阪フィルハーモニー会館' },
    { id: 394, prefecture_id: 27, search_name: '阿倍野区民,阿倍野区区民', name: '大阪市阿倍野区民センター' },
    { id: 395, prefecture_id: 27, search_name: '大阪市中央公会堂,大阪中央公会堂', name: '大阪市中央公会堂' },
    { id: 396, prefecture_id: 27, search_name: '東成区民,東成区区民', name: '大阪市立東成区民センター' },
    { id: 397, prefecture_id: 27, search_name: 'カワイ梅田,ジュエ', name: 'カワイ梅田 コンサートサロン「ジュエ」' },
    { id: 398, prefecture_id: 27, search_name: 'クレオ大阪', name: 'クレオ大阪' },
    { id: 399, prefecture_id: 27, search_name: 'シンフォニーホール', name: 'ザ・シンフォニーホール' },
    { id: 400, prefecture_id: 27, search_name: '堺市立青少年,堺市青少年,堺青少年', name: '堺市立青少年センター' },
    { id: 401, prefecture_id: 27, search_name: '吹田文化,吹田市文化,メイシアタ', name: '吹田市文化会館・メイシアター' },
    { id: 402, prefecture_id: 27, search_name: '住吉区民,住吉区区民', name: '住吉区民センター' },
    { id: 403, prefecture_id: 27, search_name: '大丸心斎橋', name: '大丸心斎橋劇場' },
    { id: 404, prefecture_id: 27, search_name: '高槻現代', name: '高槻現代劇場' },
    { id: 405, prefecture_id: 27, search_name: 'たかいし市市民文化,高石市市民文化,高石市民文化,たかいし市民文化,アプラたかいし,アプラ高石', name: 'たかいし市民文化会館 (アプラたかいし)' },
    { id: 406, prefecture_id: 27, search_name: 'アクア文化,アクアホール', name: '豊中市立アクア文化ホール' },
    { id: 407, prefecture_id: 27, search_name: 'ローズ文化,ローズホール', name: '豊中市立ローズ文化ホール' },
    { id: 408, prefecture_id: 27, search_name: '豊中市立文化,豊中市文化,豊中文化', name: '豊中市立文化芸術センター' },
    { id: 409, prefecture_id: 27, search_name: '寝屋川市立市民,寝屋川市市民,寝屋川市民', name: '寝屋川市立市民会館' },
    { id: 410, prefecture_id: 27, search_name: '寝屋川地域,寝屋川市地域,寝屋川市立地域,アルカス', name: '寝屋川市立地域交流センター アルカスホール' },
    { id: 411, prefecture_id: 27, search_name: '東大阪市男女,東大阪市立男女,イコーラム', name: '東大阪市立男女共同参画センター イコーラム' },
    { id: 412, prefecture_id: 27, search_name: '枚方市市民会館,枚方市民会館', name: '枚方市市民会館' },
    { id: 413, prefecture_id: 27, search_name: '藤井寺市立,藤井寺市市民,藤井寺市民,パープルホール', name: '藤井寺市立市民総合会館（パープルホール）' },
    { id: 414, prefecture_id: 27, search_name: 'メイプルホール', name: '箕面市立メイプルホール' },
    { id: 415, prefecture_id: 27, search_name: '守口文化,エナジー', name: '守口文化センター・エナジーホール' },
    { id: 416, prefecture_id: 27, search_name: '八尾文化,八尾市文化,プリズムホール', name: '八尾市文化会館・プリズムホール' },
    { id: 417, prefecture_id: 28, search_name: 'ame,Ame,AME,ＡＭＥ', name: 'salon de ame' },
    { id: 418, prefecture_id: 28, search_name: '相生文化,相生市文化,電通なぎさ', name: '相生市文化会館 扶桑電通なぎさホール' },
    { id: 419, prefecture_id: 28, search_name: '明石市市民,明石市立市民,明石市民,アワーズ', name: '明石市立市民会館・アワーズホール' },
    { id: 420, prefecture_id: 28, search_name: '芦屋市市民,芦屋市民,ルナホール', name: '芦屋市民センター・ルナホール' },
    { id: 421, prefecture_id: 28, search_name: '尼崎総合,尼崎市総合,アルカイック', name: '尼崎市総合文化センター・アルカイックホール' },
    { id: 422, prefecture_id: 28, search_name: '尼崎青少年,ピッコロ', name: '尼崎青少年創造劇場・ピッコロシアター' },
    { id: 423, prefecture_id: 28, search_name: '伊丹市音楽,伊丹市立音楽,伊丹音楽,アイフォニック', name: '伊丹市立音楽ホール・アイフォニック' },
    { id: 424, prefecture_id: 28, search_name: '伊丹市文化,伊丹市立文化,伊丹文化,いたみ', name: '伊丹市立文化会館・いたみホール' },
    { id: 425, prefecture_id: 28, search_name: '加古川市民,加古川市市民', name: '加古川市民会館' },
    { id: 426, prefecture_id: 28, search_name: '加古川ウェルネス,アラベスク', name: '加古川ウェルネスパーク アラベスクホール' },
    { id: 427, prefecture_id: 28, search_name: 'みつなかホール,光中ホール', name: '川西市みつなかホール' },
    { id: 428, prefecture_id: 28, search_name: '川西市文化,川西文化', name: '川西市文化会館' },
    { id: 429, prefecture_id: 28, search_name: '神戸産業振興,神戸市産業振興,ハーバー', name: '神戸市産業振興センター・ハーバーホール' },
    { id: 430, prefecture_id: 28, search_name: '東灘区区民,東灘区民,うはらホール', name: '神戸市立東灘区民センター・うはらホール' },
    { id: 431, prefecture_id: 28, search_name: '神戸新聞,松方ホール', name: '神戸新聞松方ホール' },
    { id: 432, prefecture_id: 28, search_name: '神戸文化', name: '神戸文化ホール' },
    { id: 433, prefecture_id: 28, search_name: '立灘区民,立灘区区民', name: '神戸市立灘区民ホール' },
    { id: 434, prefecture_id: 28, search_name: '神戸布引ハーブ園', name: '神戸布引ハーブ園 森のホール' },
    { id: 435, prefecture_id: 28, search_name: '郷の音,三田市総合,三田総合', name: '郷の音ホール 三田市総合文化センター' },
    { id: 436, prefecture_id: 28, search_name: '舞子ビラ神戸', name: 'シーサイドホテル舞子ビラ神戸' },
    { id: 437, prefecture_id: 28, search_name: '宝塚市文化,宝塚市立文化,宝塚文化,ベガ', name: '宝塚市立文化施設 ベガ・ホール' },
    { id: 438, prefecture_id: 28, search_name: 'たつの総合,たつの市総合,赤とんぼ', name: 'たつの市総合文化会館・赤とんぼ文化ホール' },
    { id: 439, prefecture_id: 28, search_name: 'たんば,田園交響', name: 'たんば田園交響ホール' },
    { id: 440, prefecture_id: 28, search_name: '東条文化,東条町文化,コスミック', name: '東条町文化会館・コスミックホール' },
    { id: 441, prefecture_id: 28, search_name: '西宮市市民,西宮市民,アミニティ', name: '西宮市民会館・アミニティホール' },
    { id: 442, prefecture_id: 28, search_name: '西宮市甲東,西宮甲東,甲東ホール', name: '西宮市甲東ホール' },
    { id: 443, prefecture_id: 28, search_name: '兵庫県立芸術,兵庫県芸術,兵庫芸術', name: '兵庫県立芸術文化ホール' },
    { id: 444, prefecture_id: 28, search_name: '三木山森林', name: '兵庫県立三木山森林公園' },
    { id: 445, prefecture_id: 28, search_name: '三木市文化,三木文化', name: '三木市文化会館' },
    { id: 446, prefecture_id: 28, search_name: 'リーフ,Leaf,LEAF,ＬＥＡＦ,leaf', name: 'リーフ・ホール (Leaf Hall)' },
    { id: 447, prefecture_id: 29, search_name: '當麻文化会館', name: '當麻文化会館' },
    { id: 448, prefecture_id: 29, search_name: '天理市文化,天理文化', name: '天理市文化センター' },
    { id: 449, prefecture_id: 29, search_name: '天理市市民,天理市民,やまのべホール', name: '天理市民会館・やまのべホール' },
    { id: 450, prefecture_id: 29, search_name: '橿原文化', name: '奈良県橿原文化会館' },
    { id: 451, prefecture_id: 29, search_name: '奈良県立文化,奈良県文化,奈良文化', name: '奈良県文化会館' },
    { id: 452, prefecture_id: 29, search_name: 'ならまちセンター,奈良町センター', name: '奈良市ならまちセンター' },
    { id: 453, prefecture_id: 29, search_name: '西部会館,学園前ホール', name: '奈良市西部会館市民ホール・学園前ホール' },
    { id: 454, prefecture_id: 31, search_name: '倉吉未来中心', name: '倉吉未来中心' },
    { id: 455, prefecture_id: 33, search_name: '岡山シンフォニ', name: '岡山シンフォニーホール' },
    { id: 456, prefecture_id: 33, search_name: '操南公民館', name: '岡山市立操南公民館' },
    { id: 457, prefecture_id: 34, search_name: '呉市文化,呉文化', name: '呉市文化ホール' },
    { id: 458, prefecture_id: 34, search_name: 'くれ絆', name: 'くれ絆ホール' },
    { id: 459, prefecture_id: 34, search_name: 'はつかいち,さくらぴあ,廿日市文化', name: 'はつかいち文化ホール・さくらぴあ' },
    { id: 460, prefecture_id: 34, search_name: '広島県県民文化,広島県民文化,ふくやま', name: '広島県民文化センターふくやま' },
    { id: 461, prefecture_id: 34, search_name: '広島市南区,広島南区', name: '広島市南区民文化センター' },
    { id: 462, prefecture_id: 34, search_name: '広島大学,サタケメモリアル', name: '広島大学サタケメモリアルホール' },
    { id: 463, prefecture_id: 34, search_name: '福山芸術文化,ふくやま芸術文化,リーデンローズ', name: 'ふくやま芸術文化ホール・リーデンローズ' },
    { id: 464, prefecture_id: 34, search_name: '福山市西部,福山西部', name: '福山市西部市民センター' },
    { id: 465, prefecture_id: 34, search_name: '福山市東部,福山東部', name: '福山市東部市民センター' },
    { id: 466, prefecture_id: 34, search_name: '福山市北部,福山北部', name: '福山市北部市民センター' },
    { id: 467, prefecture_id: 35, search_name: 'サンビーム', name: 'サンビームやない' },
    { id: 468, prefecture_id: 35, search_name: 'シンンフォニア岩国,いわくに', name: 'シンフォニア岩国 山口県民文化ホールいわくに' },
    { id: 469, prefecture_id: 35, search_name: '山口市民,山口市市民', name: '山口市民会館' },
    { id: 470, prefecture_id: 36, search_name: '阿南文化,阿南市文化,夢ホール', name: '阿南市文化会館・夢ホール' },
    { id: 471, prefecture_id: 36, search_name: '文化の森２１,文化の森21,21世紀館,２１世紀館', name: '徳島県立 文化の森21世紀館' },
    { id: 472, prefecture_id: 38, search_name: '松山市民,松山市市民', name: '松山市民会館' },
    { id: 473, prefecture_id: 40, search_name: 'FRITZ,fritz,Fritz,フリッツ', name: 'Studio Fritz Nathan スタジオ・フリッツ・ナタン' },
    { id: 474, prefecture_id: 40, search_name: 'アクロス福岡', name: 'アクロス福岡' },
    { id: 475, prefecture_id: 40, search_name: '石橋文化', name: '石橋文化センター' },
    { id: 476, prefecture_id: 40, search_name: 'サンリーアイ', name: '岡垣サンリーアイ' },
    { id: 477, prefecture_id: 40, search_name: '春日市ふれあい文化,春日ふれあい文化', name: '春日市ふれあい文化センター' },
    { id: 478, prefecture_id: 40, search_name: '春日市ふれあい文化,春日ふれあい文化', name: '春日市ふれあい文化センター' },
    { id: 479, prefecture_id: 40, search_name: '志免町町民,志免町民', name: '志免町町民センター' },
    { id: 480, prefecture_id: 40, search_name: '東市民センター,なみきホール', name: '東市民センター なみきホール' },
    { id: 481, prefecture_id: 40, search_name: '早良市市民,早良市民,早良図書館', name: '福岡市立早良市民センター・早良図書館' },
    { id: 482, prefecture_id: 40, search_name: '福岡市立中央,福岡市中央,福岡中央', name: '福岡市立中央市民センター' },
    { id: 483, prefecture_id: 40, search_name: '福岡県東市民,なみきスクエア,並木スクエア', name: '福岡県東市民センター なみきスクエア' },
    { id: 484, prefecture_id: 40, search_name: '福岡市立西市民,福岡市西市民,福岡西市民', name: '福岡市立西市民センター' },
    { id: 485, prefecture_id: 40, search_name: 'カルコア太宰府', name: 'プラム・カルコア太宰府' },
    { id: 486, prefecture_id: 40, search_name: '宗像市民,宗像総合市民,ユリックス', name: '宗像総合市民センター・ユリックス' },
    { id: 487, prefecture_id: 40, search_name: '若松市民,若松市市民', name: '若松市民会館' },
    { id: 488, prefecture_id: 41, search_name: '佐賀市文化,佐賀文化', name: '佐賀市文化会館' },
    { id: 489, prefecture_id: 46, search_name: '霧島市民,霧島市市民', name: '霧島市民会館' },
    { id: 490, prefecture_id: 46, search_name: '南日本新聞会館,みなみホール', name: '南日本新聞会館 みなみホール' },
    { id: 491, prefecture_id: 47, search_name: '南城文化,南城市文化,シュガー', name: '南城市文化センター・シュガーホール' },
    { id: 492, prefecture_id: 47, search_name: '西原町民,西原町町民,さわふじ未来', name: '西原町町民交流センター さわふじ未来ホール' },
    { id: 493, prefecture_id: 47, search_name: 'パレット市民劇場', name: 'パレット市民劇場' }
  ]
end
